version: '3'
services:
  client:
    env_file:
     - ./.env
    image: 'picus_client'
    stdin_open: true
    tty: true
    ports:
      - "${PORT_REACT}:3000"
    networks:
      network_1:
        ipv4_address: 10.10.0.6
        
  server:
    env_file:
     - ./.env  
    image: 'picus_server'
    stdin_open: true
    tty: true
    ports:
     - "${REACT_APP_PORT_SERVER}:8000"
    networks:
      network_1:
        ipv4_address: 10.10.0.2
        
  keycloak:
    env_file:
     - ./.env  
    image: 'alessandro123456/keycloak'
    stdin_open: true
    tty: true
    environment:
       KEYCLOAK_USER: admin
       KEYCLOAK_PASSWORD: admin
    ports:
      - "${REACT_APP_PORT_KEYCLOAK}:8080"
      
  mysql:
    env_file:
     - ./.env
    image: 'picus_mysql'
    stdin_open: true
    tty: true
    environment:
       MYSQL_ROOT_PASSWORD: password
    ports:
      - "${PORT_DB}:3306"
    networks:
      network_1:
        ipv4_address: 10.10.0.3
        
networks:
  network_1:
    ipam:
      config:
        - subnet: 10.10.0.0/24
